[target.aarch64-linux-android]
linker = "D:/androidSdk/ndk/28.0.13004108/toolchains/llvm/prebuilt/windows-x86_64/bin/aarch64-linux-android30-clang.cmd"
ar = "D:/androidSdk/ndk/28.0.13004108/toolchains/llvm/prebuilt/windows-x86_64/bin/llvm-ar.exe"
